instPckg<-function(){
   install.packages("baseline", repos="http://cran.us.r-project.org", dependencies=c("Depends"),  verbose=TRUE)
   install.packages("digest", repos="http://cran.us.r-project.org", dependencies=c("Depends"),  verbose=TRUE)
   install.packages("grid", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("import", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("latticeExtra", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("FME", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("methods", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("minpack.lm", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("NORMT3", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("signal", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
#   install.packages("sm", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("SparseM", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("wavelets", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("tcltk", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("tkrplot", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("gWidgets2", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
   install.packages("gWidgets2tcltk", repos="http://cran.us.r-project.org", dependencies=c("Depends"), verbose=TRUE)
}