mysource <- function() {
#
#     require(baseline)
     require(datasets)  #default
#     require(digest)
#     require(FME)
     require(graphics)  #default
     require(grDevices) #default
     require(grid)      #default
     require(import)
     require(lattice)
     require(latticeExtra)
     require(methods)   #default
     require(minpack.lm)
#     require(NORMT3)
#     require(signal)
     require(SparseM)
     require(stats)     #default
     require(utils)     #default
#     require(wavelets)

     require(tcltk)     #default
     require(tkrplot)
     require(gWidgets2)
     require(gWidgets2tcltk)
     options(guiToolkit="tcltk")



     source('~/R/RxpsG_2.3/R/RXPSGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSAddFitComponent.r' )
     source('~/R/RxpsG_2.3/R/XPSAnalysisGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSAnnotateGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSClass.r' )
     source('~/R/RxpsG_2.3/R/XPSCompareGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSCompareEngine.r' )
     source('~/R/RxpsG_2.3/R/XPSConstrain.r' )
     source('~/R/RxpsG_2.3/R/XPSConstraintsGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSCoreLineList.r' )
     source('~/R/RxpsG_2.3/R/XPSCustomBaseline.r' )
     source('~/R/RxpsG_2.3/R/XPSCustomPlotGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSDiffGUI.r' )     
     source('~/R/RxpsG_2.3/R/XPSElements.r' )
     source('~/R/RxpsG_2.3/R/XPSElemTabGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSEshiftGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSExportAsciiGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSExtractGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSFilterGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSFitAlgorithms.r' )
     source('~/R/RxpsG_2.3/R/XPSFitCompClass.r' )
     source('~/R/RxpsG_2.3/R/XPSFitInfoGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSFitLM.r' )
     source('~/R/RxpsG_2.3/R/XPSFitParamInfoGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSFNameList.r' )
     source('~/R/RxpsG_2.3/R/XPSGetHvalue.r' )
     source('~/R/RxpsG_2.3/R/XPSImportAsciiGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSLatticeAnnotateGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSModFitGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSMoveBaseLineGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSMoveCompGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSnlsLM.r' )
     source('~/R/RxpsG_2.3/R/XPSOverlayEngine.r' )
     source('~/R/RxpsG_2.3/R/XPSOverlayGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSPreferencesGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSProcessCoreLineGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSQuantifyGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSRead.r' )
     source('~/R/RxpsG_2.3/R/XPSRead.Genplot.r' )     
     source('~/R/RxpsG_2.3/R/XPSRead.scienta.r' )
     source('~/R/RxpsG_2.3/R/XPSRead.Oldscienta.r' )
     source('~/R/RxpsG_2.3/R/XPSRead.vamas.r' )
     source('~/R/RxpsG_2.3/R/XPSReportGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSResetAnalysisGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSampleInfoGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSaveDataGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSaveRetrieveBkp.r' )
     source('~/R/RxpsG_2.3/R/XPSSetCoreLineGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSetFNameCLineGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSetGraphDevGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSetWDGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSetWinSizeGUI.r' )     
     source('~/R/RxpsG_2.3/R/XPSSpectList.r' )
     source('~/R/RxpsG_2.3/R/XPSSpectNameChangeGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSplitGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSprucingGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSurElmtIdentifyGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSSurveyUtilities.r' )
     source('~/R/RxpsG_2.3/R/XPSSwitchBE.KE.GUI.r' )
     source('~/R/RxpsG_2.3/R/XPSTwoScalePlotGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSUtilities.r' )
     source('~/R/RxpsG_2.3/R/XPSVBTopGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSVmsCorrGUI.r' )
     source('~/R/RxpsG_2.3/R/XPSZoomCurGUI.r' )

     setwd("~/mydir/LAVORI/R/Analysis")
     xps()
}
